[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.sandh.co.in
CATALOGUE_HOST=catalogue-dev.sandh.co.in
REDIS_HOST=redis-dev.sandh.co.in
USER_HOST=user-dev.sandh.co.in
CART_HOST=cart-dev.sandh.co.in
MYSQL_HOST=mysql-dev.sandh.co.in
SHIPPING_HOST=shipping-dev.sandh.co.in
RABBITMQ_HOST=rabbitmq-dev.sandh.co.in
PAYMENT_HOST=payment-dev.sandh.co.in