- name: copy {{ component }} service
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true